### PR TITLE
Views

### PR DESCRIPTION
**Pull request by naji-97**
- [ ] Implement the design from the sneak peek wireframes
- [ ] Add style

### CODE REVIEW

**Review by codecaiine — APPROVED** [review]
Hi @naji-97 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good view implementation ✔️ 

## Optional suggestions
- [ ] [OPTIONAL] I would strongly recommend you to create a new PR next time for re-review  in order to help code reviewer to give the best review to your project 😄 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by naji-97** [comment]
Hi, Yannick-Noel AKA

you reviewed my PR and gived me the authorisation to merge it
but when I checked my progress to send the final submission I find it still
pending :
[image: image.png]

**Comment by codecaiine** [comment]
@naji-97 Sorry my internet was slow .

**Comment by naji-97** [comment]
No problem, thank you so much

**Pull request merged**
